import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { createSession } from '../src/automation/session.js';
import { authFixture } from './helpers/auth-fixture.js';
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

test('dashboard drives a real sequential run; API rejects cross-origin requests; persistent session reused', async () => {
  const port = 31387;
  const auth = await authFixture();
  const serverProfile = await mkdtemp(join(tmpdir(), 'runner-dashboard-test-'));
  const child = spawn(process.execPath, ['src/server.js'], { env: { ...process.env, PORT: String(port), RUNNER_PROFILE_DIR: serverProfile }, stdio: ['ignore', 'pipe', 'pipe'] });
  let output = ''; child.stdout.on('data', c => output += c); child.stderr.on('data', c => output += c);
  const fixture = createServer((req, res) => {
    res.setHeader('Content-Type', 'text/html');
    res.end('<button id="next" onclick="this.textContent=\'Clicked\'">Continue</button>');
  }).listen(0, '127.0.0.1');
  await new Promise(resolve => fixture.once('listening', resolve));
  const base = `http://127.0.0.1:${port}`;
  let browser;
  try {
    for (let i = 0; i < 100 && !output.includes('Browser Runner:'); i++) await sleep(50);
    assert.ok(output.includes('Browser Runner:'), output);
    assert.equal((await fetch(`${base}/api/stop`, { method: 'POST', headers: { Origin: 'https://evil.test', 'X-Runner-Request': '1' } })).status, 403);
    assert.equal((await fetch(`${base}/api/stop`, { method: 'POST' })).status, 403);
    browser = await chromium.launch({ headless: true });
    const page = await browser.newPage(); const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(base);
    assert.equal(await page.locator('#minutes').inputValue(), '15');
    assert.equal(await page.locator('#showBrowser').isChecked(), true);
    const target = `http://127.0.0.1:${fixture.address().port}`;
    await page.locator('#urls').fill(`${target}/one\n${target}/two`);
    await page.locator('#minutes').fill('0.004'); await page.locator('#delay').fill('0');
    await page.locator('#mode').selectOption('css'); await page.locator('#target').fill('#next');
    await page.locator('#showBrowser').uncheck();
    await page.locator('#start').click();
    await page.waitForFunction(() => document.querySelector('#status').textContent === 'COMPLETED', { timeout: 15000 });
    assert.equal(await page.locator('#completed').textContent(), '2');
    assert.equal(await page.locator('#percent').textContent(), '100%');
    assert.equal(await page.locator('#failed').textContent(), '0');
    await page.reload(); assert.equal(await page.locator('#minutes').inputValue(), '0.004');
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    assert.deepEqual(errors, []);
    // Drive authentication through the real dashboard and POST API.
    await page.setViewportSize({ width: 1200, height: 900 });
    await page.locator('#authEnabled').check();
    assert.equal(await page.locator('#authPassword').getAttribute('type'), 'password');
    await page.locator('#authUsername').fill(auth.authentication.username);
    await page.locator('#authPassword').fill(auth.authentication.password);
    await page.locator('#showPassword').click();
    assert.equal(await page.locator('#authPassword').getAttribute('type'), 'text');
    await page.locator('#showPassword').click();
    await page.locator('summary').click();
    await page.locator('#usernameSelector').fill('#email');
    await page.locator('#passwordSelector').fill('#secret');
    await page.locator('#loginButtonSelector').fill('#login');
    await page.locator('#urls').fill(`${auth.base}/target/one\n${auth.base}/target/two`);
    await page.locator('#minutes').fill(String(5 / 60));
    await page.locator('#mode').selectOption('text'); await page.locator('#target').fill('Continue');
    const saved = await page.evaluate(() => JSON.stringify(localStorage));
    assert.ok(!saved.includes(auth.authentication.username)); assert.ok(!saved.includes(auth.authentication.password));
    await page.locator('#start').click();
    assert.equal(await page.locator('#authPassword').inputValue(), '');
    assert.equal(await page.locator('#authUsername').inputValue(), '');
    await page.waitForFunction(() => document.querySelector('#status').textContent === 'RUNNING');
    const status = await (await fetch(`${base}/api/status`)).text();
    assert.ok(!status.includes(auth.authentication.username)); assert.ok(!status.includes(auth.authentication.password));
    await page.waitForFunction(() => document.querySelector('#status').textContent === 'COMPLETED', null, { timeout: 45000 });
    assert.equal(await page.locator('#completed').textContent(), '2');
    assert.equal(await page.locator('#failed').textContent(), '0');
    assert.equal(auth.events.filter(e => e.type === 'submit').length, 1);
    const finalStatus = await (await fetch(`${base}/api/status`)).text();
    assert.ok(!finalStatus.includes(auth.authentication.username)); assert.ok(!finalStatus.includes(auth.authentication.password));
    await page.reload();
    assert.equal(await page.locator('#authPassword').inputValue(), '');
    assert.equal(await page.locator('#authUsername').inputValue(), '');
    assert.equal(await page.locator('#usernameSelector').inputValue(), '#email');
    await page.locator('#authEnabled').uncheck();
    assert.equal(await page.locator('#authPassword').isDisabled(), true);
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    assert.deepEqual(errors, []);
    // Verify the actual profile adapter persists cookies across context restarts.
    const profile = await mkdtemp(join(tmpdir(), 'runner-session-test-'));
    const session = createSession(profile);
    let context = await session.open(false);
    await context.addCookies([{ name: 'runner-test', value: 'session-proof', url: target, expires: Date.now() / 1000 + 3600 }]);
    await context.close();
    context = await session.open(false);
    assert.ok((await context.cookies(target)).some(c => c.name === 'runner-test' && c.value === 'session-proof'));
    await context.clearCookies(); await context.close();
    await rm(profile, { recursive: true, force: true });
  } finally {
    await browser?.close();
    child.kill('SIGTERM');
    await new Promise(resolve => { if (child.exitCode !== null) resolve(); else child.once('exit', resolve); });
    await new Promise(resolve => fixture.close(resolve));
    await auth.close();
    await rm(serverProfile, { recursive: true, force: true });
  }
});
